services:
  swimmate:
    container_name: swimmate
    image: cosmtrek/air
    working_dir: /app
    environment:
      - DB_DSN=postgres://swimmate:swimmate@swimmate-db:5432/swimmate?sslmode=disable
    ports:
      - "8998:8998"
    volumes:
      - ./:/app
  swimmate-db:
    container_name: swimmate-db
    image: postgres:14
    environment:
      POSTGRES_USER: swimmate
      POSTGRES_PASSWORD: swimmate
      POSTGRES_DB: swimmate
    ports:
      - "5432:5432"
    volumes:
      - swimmate-data:/var/lib/postgresql/data
volumes:
  swimmate-data:
