name: Continuous Integration
on:
  push:
    branches:
      - main
    paths:
      - 'cmd/**'
      - 'ui/**'
      - '**.go'
      - 'go.mod'
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Run golang static analysis
        run: go vet ./...
      - name: Run additional static analysis
        uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1.1"

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - run: go build ./...
